function out1 = hessc8(in1)
%HESSC8
%    OUT1 = HESSC8(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    26-Nov-2023 17:55:07

x1 = in1(:,1);
x4 = in1(:,4);
t2 = x1.*6.278887804878049e+1;
t3 = -t2;
out1 = reshape([x4.*(-6.278887804878049e+1)+9.095625e-3,0.0,0.0,t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3,0.0,0.0,0.0],[4,4]);
