function out1 = hessc6(in1)
%HESSC6
%    OUT1 = HESSC6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    26-Nov-2023 17:55:07

x1 = in1(:,1);
x4 = in1(:,4);
t2 = x1.*4.506549593495935e+1;
t3 = -t2;
out1 = reshape([x4.*(-4.506549593495935e+1)+2.02125e-2,0.0,0.0,t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3,0.0,0.0,0.0],[4,4]);
