function out1 = hessc7(in1)
%HESSC7
%    OUT1 = HESSC7(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    26-Nov-2023 17:55:07

x1 = in1(:,1);
x4 = in1(:,4);
t2 = x1.*4.506549593495935e+1;
out1 = reshape([x4.*4.506549593495935e+1+2.02125e-2,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0],[4,4]);
