function [optOut,gradLSP] = objectiveFunction(in1)
%objectiveFunction
%    [optOut,gradLSP] = objectiveFunction(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    26-Nov-2023 17:55:05

x1 = in1(:,1);
optOut = -x1;
if nargout > 1
    gradLSP = [-1.0;0.0;0.0;0.0];
end
