function hessLSP = objectiveHessian(in1)
%objectiveHessian
%    hessLSP = objectiveHessian(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    26-Nov-2023 17:55:05

hessLSP = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
